services:
  database:
    image: mysql:9.0
    volumes:
      - news_website:/var/lib/mysql
    ports:
      - '3375:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: news
      MYSQL_USER: nam
      MYSQL_PASSWORD: Ex@mple12345

volumes:
  news_website: